#!/bin/bash
# check-asset-drift.sh — verify the installer's asset pipeline cannot silently
# rot (gap found 2026-07-12: onboarded projects got a stale contract and NO
# OpenCode guard layer, and nothing in CI noticed).
#
# Three independent checks:
#   1. MANIFEST PARITY + COVERAGE — the dir/file lists in
#      tools/multi-cli-install/scripts/sync-assets.ts (what gets bundled) and
#      src/installer/copy-framework.ts (what gets installed) must agree, and
#      both must include every REQUIRED entry (.opencode, AGENTS.md, ...).
#      This is the check that fails the actual 2026-07-12 defect class: a
#      framework path added to the repo but never to the ship manifests.
#   2. NO COMMITTED GENERATED ASSETS — tools/multi-cli-install/assets/ is a
#      build artifact (regenerated by prebuild). A committed copy goes stale
#      the moment its source changes (a stale assets/AGENTS.md describing
#      protocol v2 shipped this way). git ls-files must be empty.
#   3. CONTENT DRIFT — if an assets/ tree exists on disk, EVERY file under it
#      is glob-walked (no hardcoded file list — new files are covered
#      automatically) and must byte-match its source at the repo root, and
#      every manifest entry must be present. Catches stale local build dirs.
#      In CI, gates.yml regenerates assets immediately before this check.
#
# Usage (from anywhere):  bash .ai/tools/check-asset-drift.sh
# Env override:           REPO_ROOT=/path/to/repo
# Exit: 0 = PASS, 1 = drift/coverage failure, 2 = environment error.

set -u

REPO_ROOT="${REPO_ROOT:-}"
if [ -z "$REPO_ROOT" ]; then
  d="$(cd "$(dirname "$0")" && pwd)"
  for _ in $(seq 1 10); do
    if [ -d "$d/.ai" ] && [ -d "$d/tools/multi-cli-install" ]; then REPO_ROOT="$d"; break; fi
    d="$(dirname "$d")"
  done
fi
[ -n "$REPO_ROOT" ] && [ -d "$REPO_ROOT/tools/multi-cli-install" ] || {
  echo "check-asset-drift: cannot locate repo root (set REPO_ROOT)"; exit 2;
}
cd "$REPO_ROOT" || exit 2

PKG="tools/multi-cli-install"
SYNC="$PKG/scripts/sync-assets.ts"
COPY="$PKG/src/installer/copy-framework.ts"
ASSETS="$PKG/assets"

[ -f "$SYNC" ] || { echo "check-asset-drift: missing $SYNC"; exit 2; }
[ -f "$COPY" ] || { echo "check-asset-drift: missing $COPY"; exit 2; }

fail=0
err() { echo "FAIL: $*"; fail=$((fail + 1)); }

# Extract single-quoted entries from the lines defining a manifest list.
# $1 = file, $2 = regex anchoring the list's opening line.
extract_list() {
  awk "/$2/{f=1} f{print} f&&/\]/{exit}" "$1" | grep -o "'[^']*'" | tr -d "'" | sort
}

sync_dirs=$(extract_list "$SYNC" "for \(const d of")
sync_files=$(extract_list "$SYNC" "for \(const f of")
copy_dirs=$(extract_list "$COPY" "FRAMEWORK_DIRS =")
copy_files=$(extract_list "$COPY" "FRAMEWORK_FILES =")

[ -n "$sync_dirs" ] || { echo "check-asset-drift: could not parse dir list from $SYNC"; exit 2; }
[ -n "$copy_dirs" ] || { echo "check-asset-drift: could not parse FRAMEWORK_DIRS from $COPY"; exit 2; }

# --- check 1: manifest parity + required coverage -------------------------
if [ "$sync_dirs" != "$copy_dirs" ]; then
  err "dir manifest diverged: sync-assets.ts [$(echo $sync_dirs | tr '\n' ' ')] vs copy-framework.ts [$(echo $copy_dirs | tr '\n' ' ')]"
fi
# File lists allow exactly ONE known asymmetry: sync-assets.ts bundles
# .gitignore (plus a no-dot twin) because npm strips it from tarballs, while
# copy-framework.ts must NOT blind-copy it — adapt-policy.ts MERGES it into
# the target's existing .gitignore instead. Any other divergence fails.
sync_files_normalized=$(echo "$sync_files" | grep -vx '.gitignore' || true)
if [ "$sync_files_normalized" != "$copy_files" ]; then
  err "file manifest diverged (beyond the deliberate .gitignore asymmetry): sync-assets.ts vs copy-framework.ts"
fi

# Dirs that MUST ship — .opencode carries the guard layer (ADR-0002 amendment
# 2026-07-09). Add entries here when the framework gains a new shippable dir.
for req in .ai .claude .kimi .kiro .opencode; do
  echo "$sync_dirs" | grep -qx "$req" || err "required dir '$req' missing from sync-assets.ts manifest"
  echo "$copy_dirs" | grep -qx "$req" || err "required dir '$req' missing from copy-framework.ts FRAMEWORK_DIRS"
done
for req in AGENTS.md opencode.json; do
  echo "$sync_files" | grep -qx "$req" || err "required file '$req' missing from sync-assets.ts manifest"
  echo "$copy_files" | grep -qx "$req" || err "required file '$req' missing from copy-framework.ts FRAMEWORK_FILES"
done

# --- check 2: no committed generated assets -------------------------------
committed=$(git ls-files "$ASSETS")
if [ -n "$committed" ]; then
  err "$ASSETS/ is a build artifact but these files are committed (they WILL go stale):"$(printf '\n%s' "$committed" | sed 's/^/    /')
fi

# --- check 3: content drift of any on-disk asset tree (glob walk) ----------
checked=0
if [ -d "$ASSETS" ]; then
  while IFS= read -r f; do
    rel="${f#"$ASSETS"/}"
    src="$rel"
    [ "$rel" = "gitignore" ] && src=".gitignore"  # no-dot twin of .gitignore (npm strips it)
    checked=$((checked + 1))
    if [ ! -f "$src" ]; then
      err "asset has no source: $f"
    elif ! diff -q "$src" "$f" >/dev/null 2>&1; then
      err "DRIFT: $src -> $f"
    fi
  done < <(find "$ASSETS" -type f | sort)

  while IFS= read -r d; do
    [ -e "$ASSETS/$d" ] || err "manifest dir missing from asset tree: $d"
  done <<< "$sync_dirs"
  while IFS= read -r f; do
    [ -e "$ASSETS/$f" ] || err "manifest file missing from asset tree: $f"
  done <<< "$sync_files"
else
  echo "NOTE: $ASSETS/ not on disk — content comparison skipped"
  echo "      (generate with: cd $PKG && npx tsx scripts/sync-assets.ts)"
fi

echo "Checked: $checked asset files, Failures: $fail"
[ "$fail" -eq 0 ] && { echo "check-asset-drift: PASS"; exit 0; } || exit 1
